### ISSUE TITLE
Signatures does not send requests to test vulnerabilities

### ISSUE THREAD

**Issue by omarhashem123** [jaeles-project/jaeles-signatures#27]
## I was using option --proxy to test some signatures and this signatures doesn't work(requests does not sent)
fuzz/sqli/sqli-time.yaml
fuzz/lfi/lfi-param-01.yaml
fuzz/lfi/lfi-header-01.yaml
fuzz/lfi/lfi-header-windows-01.yaml
fuzz/common/host-header-injection.yaml
fuzz/open-redirect-param.yaml
fuzz/open-redirect-path.yaml
fuzz/random/common-error-02.yaml
fuzz/random/random-fuzz-headers.yaml
fuzz/random/random-fuzz-param-02.yaml

**Comment by j3ssie** [comment]
These are signatures level 2 to reduce noise in normal run. You might need to run `jaeles scan .. -L 2 ...` to activate these ones.
