### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by z3r0s3c** [jaeles-project/jaeles-signatures#3]
Receiving this error all the time `fatal error: concurrent map writes

goroutine 2340 [running]:
runtime.throw(0x11ba60c, 0x15)
	/usr/lib/go-1.14/src/runtime/panic.go:1114 +0x72 fp=0xc0004786f0 sp=0xc0004786c0 pc=0x43aab2
runtime.mapassign_faststr(0x105fa00, 0xc00016b4a0, 0xc000373e0a, 0x5, 0x4)
	/usr/lib/go-1.14/src/runtime/map_faststr.go:211 +0x3f7 fp=0xc000478758 sp=0xc0004786f0 pc=0x41aa77
github.com/jaeles-project/jaeles/core.RunConclude.func12(0xc0004d0600, 0x0, 0x0, 0x5, 0x1181ea0, 0xc0006e6000, 0xc000844660, 0x2, 0x2, 0xc0000a1e70, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/conclusions.go:121 +0x15b fp=0xc000478858 sp=0xc000478758 pc=0xd7a2cb
github.com/robertkrimen/otto.(*_object).call(0xc0005cdc20, 0x5, 0x1181ea0, 0xc0006e6000, 0xc000844660, 0x2, 0x2, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/type_function.go:201 +0x711 fp=0xc000478c28 sp=0xc000478858 pc=0xadb041
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeCallExpression(0xc0004d0600, 0xc000844600, 0x0, 0x0, 0x0, 0xc000478f80, 0x413c26, 0xc000490570)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:244 +0x470 fp=0xc000478eb8 sp=0xc000478c28 pc=0xa80230
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeExpression(0xc0004d0600, 0x13988e0, 0xc000844600, 0x451a2e, 0xc000490570, 0x10)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_expression.go:44 +0x4fa fp=0xc000478f70 sp=0xc000478eb8 pc=0xa7e71a
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatement(0xc0004d0600, 0x13989a0, 0xc0004905b0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:62 +0xe55 fp=0xc000479190 sp=0xc000478f70 pc=0xa83b05
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeStatementList(0xc0004d0600, 0xc000490580, 0x1, 0x1, 0x6e6f736a2f6e6f69, 0xc000844540, 0x0)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate_statement.go:121 +0x8e fp=0xc0004791f8 sp=0xc000479190 pc=0xa8403e
github.com/robertkrimen/otto.(*_runtime).cmpl_evaluate_nodeProgram(0xc0004d0600, 0xc00017a0e0, 0x0, 0x0, 0x0, 0x0)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/cmpl_evaluate.go:17 +0xf8 fp=0xc000479268 sp=0xc0004791f8 pc=0xa7d858
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval.func1()
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:785 +0x44 fp=0xc0004792b0 sp=0xc000479268 pc=0xaf2414
github.com/robertkrimen/otto.catchPanic(0xc000479350, 0x0, 0x0)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/error.go:251 +0x57 fp=0xc0004792e0 sp=0xc0004792b0 pc=0xa8c2f7
github.com/robertkrimen/otto.(*_runtime).cmpl_runOrEval(0xc0004d0600, 0x100f000, 0xc000490540, 0x0, 0x0, 0xc000479300, 0x41186b, 0x10, 0x100ee40, 0x1181e01, ...)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:784 +0x10f fp=0xc000479388 sp=0xc0004792e0 pc=0xad28df
github.com/robertkrimen/otto.(*_runtime).cmpl_run(...)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/runtime.go:797
github.com/robertkrimen/otto.Otto.Run(0x0, 0xc0004d0600, 0x100f000, 0xc000490540, 0x1027f20, 0xc0004904b0, 0x0, 0x0, 0xc00033ea80)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/otto.go:295 +0x53 fp=0xc0004793f0 sp=0xc000479388 pc=0xac6ec3
github.com/jaeles-project/jaeles/core.RunConclude(0xc00048f420, 0x19, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/conclusions.go:125 +0x63a fp=0xc000479458 sp=0xc0004793f0 pc=0xd5d59a
github.com/jaeles-project/jaeles/core.RunConclusions(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/conclusions.go:20 +0x14d fp=0xc000479bd0 sp=0xc000479458 pc=0xd5cf0d
github.com/jaeles-project/jaeles/cmd.DoAnalyze(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:406 +0xe0 fp=0xc00047a5e0 sp=0xc000479bd0 pc=0xec3210
github.com/jaeles-project/jaeles/cmd.parallelSending(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:386 +0x464 fp=0xc00047bd60 sp=0xc00047a5e0 pc=0xec2e44
github.com/jaeles-project/jaeles/cmd.parallelJob(...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:343
github.com/jaeles-project/jaeles/cmd.runParallel.func1(0x10e6300, 0xc000190800)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:301 +0x166 fp=0xc00047df80 sp=0xc00047bd60 pc=0xec4266
github.com/panjf2000/ants.(*goWorkerWithFunc).run.func1(0xc0008593b0)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/worker_func.go:71 +0xac fp=0xc00047dfd8 sp=0xc00047df80 pc=0xd95a8c
runtime.goexit()
	/usr/lib/go-1.14/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00047dfe0 sp=0xc00047dfd8 pc=0x46a281
created by github.com/panjf2000/ants.(*goWorkerWithFunc).run
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/worker_func.go:49 +0x4c

goroutine 1 [sync.Cond.Wait]:
runtime.goparkunlock(...)
	/usr/lib/go-1.14/src/runtime/proc.go:310
sync.runtime_notifyListWait(0xc0005b8c50, 0x95)
	/usr/lib/go-1.14/src/runtime/sema.go:513 +0xf8
sync.(*Cond).Wait(0xc0005b8c40)
	/usr/lib/go-1.14/src/sync/cond.go:56 +0x9d
github.com/panjf2000/ants.(*PoolWithFunc).retrieveWorker(0xc00017ff40, 0xc0005a23e8)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool_func.go:283 +0x1c6
github.com/panjf2000/ants.(*PoolWithFunc).Invoke(0xc00017ff40, 0x10e6300, 0xc000740000, 0xc000740000, 0x0)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool_func.go:184 +0x37
github.com/jaeles-project/jaeles/cmd.runParallel(0xc0003cc000, 0x1a4, 0x200)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:333 +0x666
github.com/jaeles-project/jaeles/cmd.runScan(0xc000266580, 0xc00033ea10, 0x0, 0x7, 0x0, 0x0)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:139 +0x37f
github.com/spf13/cobra.(*Command).execute(0xc000266580, 0xc00033e9a0, 0x7, 0x7, 0xc000266580, 0xc00033e9a0)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1b5be20, 0x449a9a, 0x1b70aa0, 0xc000000180)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/root/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/jaeles-project/jaeles/cmd.Execute()
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/root.go:33 +0x31
main.main()
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/main.go:6 +0x20

goroutine 19 [chan receive]:
github.com/panjf2000/ants.(*Pool).periodicallyPurge(0xc0000c0900)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool.go:84 +0x1ff
created by github.com/panjf2000/ants.NewPool
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool.go:163 +0x198

goroutine 21 [select]:
database/sql.(*DB).connectionOpener(0xc00015c600, 0x13b2780, 0xc00035c6c0)
	/usr/lib/go-1.14/src/database/sql/sql.go:1052 +0xe8
created by database/sql.OpenDB
	/usr/lib/go-1.14/src/database/sql/sql.go:722 +0x15d

goroutine 22 [select]:
database/sql.(*DB).connectionResetter(0xc00015c600, 0x13b2780, 0xc00035c6c0)
	/usr/lib/go-1.14/src/database/sql/sql.go:1065 +0xfb
created by database/sql.OpenDB
	/usr/lib/go-1.14/src/database/sql/sql.go:723 +0x193

goroutine 8 [sleep]:
time.Sleep(0x2540be400)
	/usr/lib/go-1.14/src/runtime/time.go:188 +0xba
github.com/jaeles-project/jaeles/core.Background(0xc0004c6470, 0xd, 0x11c1b03, 0x1a, 0xc00048f7c0, 0x16, 0xc00048f7e0, 0x17, 0xc00048f800, 0x18, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/background.go:18 +0x74
github.com/jaeles-project/jaeles/cmd.runScan.func1()
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:87 +0x50
created by github.com/jaeles-project/jaeles/cmd.runScan
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:85 +0x889

goroutine 9 [chan receive]:
github.com/panjf2000/ants.(*PoolWithFunc).periodicallyPurge(0xc00017ff40)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool_func.go:87 +0x1ff
created by github.com/panjf2000/ants.NewPoolWithFunc
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/pool_func.go:172 +0x1bf

goroutine 2339 [runnable]:
github.com/robertkrimen/otto._newContext(0xc0004dc300)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/inline.go:1380 +0x8e93
github.com/robertkrimen/otto.newContext(0x7fe8f179c7d0)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/global.go:51 +0x13e
github.com/robertkrimen/otto.New(0x100f000)
	/root/go/pkg/mod/github.com/robertkrimen/otto@v0.0.0-20191219234010-c382bd3c16ff/otto.go:246 +0x26
github.com/jaeles-project/jaeles/core.RunDetector(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/detecter.go:23 +0x80
github.com/jaeles-project/jaeles/core.Analyze(0xc0004c6470, 0xd, 0x11c1b03, 0x1a, 0xc00048f7c0, 0x16, 0xc00048f7e0, 0x17, 0xc00048f800, 0x18, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/core/analyze.go:29 +0x11c
github.com/jaeles-project/jaeles/cmd.DoAnalyze(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:408 +0x112
github.com/jaeles-project/jaeles/cmd.parallelSending(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:386 +0x464
github.com/jaeles-project/jaeles/cmd.parallelJob(...)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:343
github.com/jaeles-project/jaeles/cmd.runParallel.func1(0x10e6300, 0xc000935800)
	/root/go/pkg/mod/github.com/jaeles-project/jaeles@v0.0.0-20200426060809-5295c2c2b111/cmd/scan.go:301 +0x166
github.com/panjf2000/ants.(*goWorkerWithFunc).run.func1(0xc000859380)
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/worker_func.go:71 +0xac
created by github.com/panjf2000/ants.(*goWorkerWithFunc).run
	/root/go/pkg/mod/github.com/panjf2000/ants@v1.3.0/worker_func.go:49 +0x4c
`

**Comment by j3ssie** [comment]
What signatures and Jaeles version did you use?

**Comment by z3r0s3c** [comment]
Signatures : secret-path.yaml 
version : beta v0.8 

Thanks!

**Comment by j3ssie** [comment]
Opps that happened because I update new syntax for signatures but didn't update it in this repo yet.

Can you try the latest of that signature again from there https://github.com/jaeles-project/jaeles-signatures/blob/master/sensitive/secret-path.yaml

**Comment by z3r0s3c** [comment]
Works fine, thank you so much!
